version: '3.8'

services:
  database:
    build: 
      context: ./database
      dockerfile: Dockerfile
    image: iothub_database-image:latest
    container_name: iothub_database
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    volumes:
      - database-volume:/var/lib/postgresql/data
    network_mode: "host"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: iothub_backend-image:latest
    depends_on:
      database:
        condition: service_healthy
    container_name: iothub_backend
    env_file:
      - .env
    network_mode: "host"
    restart: always
    volumes:
      - ./backend:/app
      - /app/node_modules
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/ || exit 1"]
      interval: 1h
      timeout: 5s
      retries: 1
      start_period: 10s

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: iothub_frontend-image:latest
    container_name: iothub_frontend
    depends_on:
      - backend
    network_mode: "host"
    volumes:
      - ./frontend:/app
      - /app/node_modules

volumes:
  database-volume:
