version: '3.8'

services:
  database:
    build: 
       context: ./database
       dockerfile: Dockerfile
    image: iothub_database-image:latest
    container_name: iothub_database
    environment:
      - POSTGRES_DB=${DB_NAME}  
      - POSTGRES_USER=${DB_USER}  
      - POSTGRES_PASSWORD=${DB_PASS} 
    volumes:
      - ./database/storage:/var/lib/postgresql/data  
    networks:
      - iot-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend  
      dockerfile: Dockerfile  
    image: iothub_backend-image:latest
    depends_on:
      database:
        condition: service_healthy  # ให้รอ database พร้อมก่อน
    container_name: iothub_backend  
    env_file:
      - .env  
    ports:
      - "8000:8000"
    networks:
      - iot-network  

networks:
  iot-network:
