version: '3.8'

services:
  database:
    build: 
       context: ./database
       dockerfile: Dockerfile
    image: iothub_database-image:latest
    container_name: iothub_database
    environment:
      - POSTGRES_DB=${DB_NAME}  
      - POSTGRES_USER=${DB_USER}  
      - POSTGRES_PASSWORD=${DB_PASS} 
    volumes:
      - ./database/storage:/var/lib/postgresql/data  
    networks:
      - iot-network

  backend:
    build:
      context: ./backend  
      dockerfile: Dockerfile  
    image: iothub_backend-image:latest
    depends_on:
      - database 
    container_name: iothub_backend  
    env_file:
      - .env  
    ports:
      - "8000:8000"
    networks:
      - iot-network  

networks:
  iot-network:
