version: '3.8'

services:
  database:
    build: 
       context: ./database
    container_name: database  
    environment:
      - POSTGRES_DB:${DB_NAME}  
      - POSTGRES_USER:${DB_USER}  
      - POSTGRES_PASSWORD:${DB_PASS} 
    volumes:
      - ./database:/var/lib/postgresql/data  
    networks:
      - iot-network   
    
  backend:
    build:
      context: ./backend  
      dockerfile: Dockerfile  
    image: iothub_backend:latest
    container_name: backend   
    env_file:
      - .env  
    ports:
      - "8000:8000"
    networks:
      - iot-network  

networks:
  iot-network:
